=== klkvsk/onphp-services/services.dtd
<!ELEMENT serviceconfiguration (servicecontainer|enum|structure)*>

<!ELEMENT servicecontainer (service)*>
<!ATTLIST servicecontainer
        name        CDATA #REQUIRED
>

<!ELEMENT service (access|action)*>
<!ATTLIST service
        name        CDATA #REQUIRED
        http-path   CDATA #REQUIRED
>

<!ELEMENT access (allow)*>
<!ATTLIST access
        override    (true|false) "false"
>

<!ELEMENT allow EMPTY>
<!ATTLIST allow
        type        CDATA #REQUIRED
>


<!ELEMENT action (param|return|access)*>
<!ATTLIST action
        name        CDATA #REQUIRED
        http-method CDATA #REQUIRED
        http-path   CDATA #REQUIRED
>

<!ELEMENT param EMPTY>
<!ATTLIST param
        default     CDATA #IMPLIED
        from        (query|body|route|session|cookie|header) "query"
        name        CDATA #REQUIRED
        required    (true|false) "false"
        type        CDATA #REQUIRED
>

<!ELEMENT return EMPTY>
<!ATTLIST return
        array       (true|false) "false"
        type        CDATA #REQUIRED
>

<!ELEMENT enum (value)*>
<!ATTLIST enum
        name        CDATA #REQUIRED
>

<!ELEMENT value EMPTY>
<!ATTLIST value
        id          CDATA #REQUIRED
        const       CDATA #REQUIRED
        name        CDATA #IMPLIED
>

<!ELEMENT structure (property)*>
<!ATTLIST structure
        extends     CDATA #IMPLIED
        name        CDATA #REQUIRED
>

<!ELEMENT property (#PCDATA)>
<!ATTLIST property
        name        CDATA #REQUIRED
        type        CDATA #REQUIRED
        required    CDATA #IMPLIED
        size        CDATA #IMPLIED
        default     CDATA #IMPLIED
>

=== klkvsk/onphp-services/example/blog.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE serviceconfiguration SYSTEM "services.dtd">
<serviceconfiguration>
    <servicecontainer name="Public">

        <service name="Articles" http-path="articles">

            <!-- GET /articles/list/ -->
            <action name="getList" http-method="GET" http-path="list">
                <param name="pagination" type="PaginationStruct" required="false" />
                <param name="tag" type="String" required="false"/>
                <param name="search" type="String" required="false"/>
                <return type="Article[]"  />
            </action>

            <!-- GET /articles/1/ -->
            <action name="getArticle" http-method="GET" http-path=":id">
                <param from="route" name="id" type="Integer" />
                <return type="Article" />
            </action>

            <!-- POST /articles/tags/ -->
            <action name="getTags" http-method="GET" http-path="tags">
                <return type="Tag[]" />
            </action>

        </service>

        <service name="Comments" http-path="comments">
            <action name="getList" http-method="GET" http-path=":articleId">
                <param from="route" name="articleId" type="Integer" required="true" />
                <return type="Comment[]" />
            </action>

            <action name="addComment" http-method="POST" http-path=":articleId">
                <param from="route" name="articleId" type="Integer" required="true" />
                <param from="query" name="comment" type="CommentForm" required="true" />
                <return type="Comment[]" />
            </action>
        </service>

    </servicecontainer>

    <servicecontainer name="Admin">
        <service name="Articles" http-path="articles">
            <action name="addArticle" http-method="POST" http-path="">
                <param from="query" name="article" type="ArticleForm" required="true" />
                <return type="Article" />
            </action>
            <action name="deleteArticle" http-method="DELETE" http-path=":articleId">
                <param from="query" name="articleId" type="Integer" />
                <return type="Boolean" />
            </action>
        </service>
    </servicecontainer>

</serviceconfiguration>

=== klkvsk/onphp-services/example/templates.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE serviceconfiguration SYSTEM "services.dtd">
<serviceconfiguration>

    <structure name="List(T)">
        <property name="items" type="T[]" />
        <property name="count" type="Integer" />
    </structure>

    <structure name="Cat">
        <property name="name" type="String" />
    </structure>

    <structure name="Dog">
        <property name="name" type="String" />
    </structure>

    <structure name="Holder">
        <property name="cats" type="List(Cat)" />
        <property name="dogs" type="List(Dog)" />
    </structure>

</serviceconfiguration>

=== klkvsk/onphp-services/example/fileserver.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE serviceconfiguration SYSTEM "services.dtd">
<serviceconfiguration>

    <structure name="UploadResult">
        <property name="fileId" type="String" required="true" />
    </structure>

    <enum name="FileType">
        <value id="image" const="IMAGE" />
        <value id="video" const="VIDEO" />
        <value id="audio" const="AUDIO" />
    </enum>

    <enum name="ThumbnailSize">
        <value id="s" const="SMALL" />
        <value id="m" const="MEDIUM" />
        <value id="l" const="LARGE" />
    </enum>

    <structure name="FileInfo">
        <property name="fileId" type="String" required="true" />
        <property name="fileType" type="FileType" required="true" />
        <property name="image" type="ImageFileInfo" required="false" />
        <property name="video" type="VideoFileInfo" required="false" />
        <property name="audio" type="AudioFileInfo" required="false" />
    </structure>

    <structure name="Image">
        <property name="format" type="ImageFormat" required="true" />
        <property name="width" type="Integer" required="true" />
        <property name="height" type="Integer" required="true" />
        <property name="url" type="String" required="true" />
    </structure>

    <structure name="Thumbnail" extends="Image">
        <property name="size" type="ThumbnailSize" required="true" />
    </structure>

    <structure name="ImageFileInfo">
        <property name="original" type="Image" required="true" />
        <property name="thumbnails" type="Thumbnail[]" />
    </structure>

    <structure name="VideoPreview">
        <property name="size" type="ThumbnailSize" required="true" />
        <property name="frames" type="Image[]" />
    </structure>

    <structure name="VideoFileInfo">
        <property name="original" type="Video" required="true" />
        <property name="previews" type="VideoPreview[]" />
    </structure>

    <servicecontainer name="FileServer">
        <generator type="php" out="backend/src/classes/" />
        <generator type="typescript" out="frontend/src/classes/" />

        <service name="Images" http-path="image">
            <!-- GET /images/123 -->
            <action name="getImage" http-method="GET" http-path=":fileId">
                <param from="route" name="fileId" type="String" required="true" />
                <return type="String" />
            </action>
            <!-- GET /images/123/s -->
            <action name="getThumbnail" http-method="GET" http-path=":fileId/:size">
                <param from="route" name="fileId" type="String" required="true" />
                <param from="route" name="size" type="ThumbnailSize" required="true" />
                <return type="String" />
            </action>
        </service>

        <service name="Videos" http-path="video">
            <!-- GET /video/123/ -->
            <action name="getVideo" http-method="GET" http-path=":fileId">
                <param from="route" name="fileId" type="String" required="true" />
                <return type="String" />
            </action>
            <!-- GET /video/123/s/1 -->
            <action name="getPreview" http-method="GET" http-path=":fileId/:size/:frame">
                <param from="route" name="fileId" type="String" required="true" />
                <param from="route" name="size" type="ThumbnailSize" required="true" />
                <param from="route" name="frame" type="Integer" required="true" />
                <return type="String" />
            </action>
        </service>

        <service name="Api" http-path="api">

            <!-- POST /api/upload/-->
            <action name="upload" http-method="POST" http-path="upload">
                <param from="query" name="file" type="String" required="false" />
                <return type="UploadResult" />
            </action>

            <!-- GET /api/info/:fileId -->
            <action name="getInfo" http-method="GET" http-path="info/:fileId">
                <param from="route" name="fileId" type="String" required="true" />
                <return type="FileInfo" />
            </action>

            <!-- GET /api/delete/:fileId -->
            <action name="deleteFile" http-method="GET" http-path="delete/:fileId">
                <param from="route" name="fileId" type="String" required="true" />
                <return type="void" />
            </action>

        </service>

    </servicecontainer>

</serviceconfiguration>

=== klkvsk/onphp-services/example/structures.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE serviceconfiguration SYSTEM "services.dtd">
<serviceconfiguration>
    <structure name="TypesTestStruct">
        <!-- simple types -->
        <property name="bool" type="Boolean" />
        <property name="int" type="Integer" />
        <property name="float" type="Float" />
        <property name="string" type="String" />

        <!-- dates and times -->
        <property name="date" type="Date" />
        <property name="timestamp" type="Timestamp" />
        <!--<property name="time" type="Time" />-->

        <!-- untyped data structures -->
        <property name="struct" type="TypesTestStruct" />
    </structure>

    <structure name="ArraysTestStruct">
        <!-- simple types -->
        <property name="bool" type="Boolean[]" />
        <property name="int" type="Integer[]" />
        <property name="float" type="Float[]" />
        <property name="string" type="String[]" />

        <!-- dates and times -->
        <property name="date" type="Date[]" />
        <property name="timestamp" type="Timestamp[]" />
        <!--<property name="time" type="Time" />-->

        <!-- untyped data structures -->
        <property name="struct" type="TypesTestStruct[]" />

    </structure>

</serviceconfiguration>

=== klkvsk/onphp-services/example/services.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE serviceconfiguration SYSTEM "services.dtd">
<serviceconfiguration>
    <servicecontainer name="Api">
        <!--
         Здесь мы определяем, какие сервисы у нас есть, как к ним обращаться и что они возвращают
         По сути, сервисы - как контроллеры, только всё RESTful.
         По метаописанию генерятся: 1) интерфейс для PHP, который нужно заимплементить 2) готовый сервис для ангулара
        -->
        <service name="Users" http-path="users">
            <access>
                <allow type="Admin" />
            </access>

            <!-- GET /users/list/ -->
            <action name="getList" http-method="GET" http-path="list">
                <param name="pagination" type="PaginationStruct" required="false" />
                <param name="search" type="String" required="false"/>
                <return type="PaginatedResult<User>"  />
            </action>

            <!-- GET /users/1/ -->
            <action name="get" http-method="GET" http-path=":userId">
                <param name="userId" type="Integer" required="true" />
                <return type="SourceInfoStruct" />
            </action>

            <!-- POST /users/ -->
            <action name="add" http-method="POST" http-path="">
                <param name="user" type="User" />
                <return type="Boolean" />
            </action>

            <!-- POST /users/1 -->
            <action name="save" http-method="POST" http-path=":userId">
                <param from="route" name="userId" type="Integer" />
                <param from="query" name="data" type="SourceEditStruct" />
                <return type="SourceInfoStruct" />
            </action>

            <!-- POST /users/1/status -->
            <action name="setStatus" http-method="POST" http-path=":userId/status">
                <param name="userId" from="route" type="Integer" />
                <param name="status" type="UserStatus" />
                <return type="Boolean" />
            </action>

            <!-- DELETE /users/1 -->
            <action name="drop" http-method="DELETE" http-path=":userId">
                <param name="userId" from="route" type="Integer" />
                <return type="Boolean" />
            </action>

        </service>

        <service name="Posts" http-path="posts">
            <!-- GET /posts/list -->
            <action name="list" http-method="GET" http-path="list">
                <return type="PaginatedResult<Post>" />
            </action>

            <!-- GET /posts/1 -->
            <action name="view" http-method="GET" http-path=":postId">
                <param from="route" name="postId" type="Integer" required="true" />
                <return type="Post" />
            </action>
        </service>
    </servicecontainer>

</serviceconfiguration>
